### ISSUE TITLE
好像，无法运行？

### ISSUE THREAD

**Issue by beixibaobao** [ybw2016v/bilibili2notes#7]
时间超过9个月没更新的项目，我尝试了一下run，发现无法运行。

＞＞＞StuartRiki_bot
Extime:-1
39471072
Traceback (most recent call last):
  File ＂/bot/bilibili/bilibili2notes/bili2notes.py＂, line 44, in ＜module＞
    doglist=getdynamic(dogconf.Uid)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File ＂/bot/bilibili/bilibili2notes/bd.py＂, line 20, in getdynamic
    for itemdog in res_text[＂data＂][＂cards＂]:
TypeError: ＇NoneType＇ object is not iterable
也许是我太菜了，希望教教，或者是开发者还会不会更新()

**Comment by ybw2016v** [comment]
B站换接口了，旧接口可能不能用了。

**Comment by ybw2016v** [comment]
已经修好了，手动在配置文件里添加一下cookie就可以了。
